"""add comments table

Revision ID: 305b120ceb16
Revises: c58f38d0a5aa
Create Date: 2026-05-16 21:12:20.094405

Adds page-level comments with reply (parent_comment_id self-FK) and resolve
(resolved_at) support. RLS tenant_isolation mirrors revisions/attachments
(node_id-indirect), so comments are scoped to the active org like every other
node-owned table.

The autogenerated drop_index ops for nodes/org_memberships were removed: those
partial indexes are created via raw SQL in earlier migrations and are absent
from ORM metadata, so Alembic falsely flags them as dropped.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import text

from alembic import op

revision: str = "305b120ceb16"
down_revision: str | Sequence[str] | None = "c58f38d0a5aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_UNSET = (
    "current_setting('app.current_org', true) IS NULL"
    " OR current_setting('app.current_org', true) = ''"
)
_VIA_WORKSPACE = "org_id = current_setting('app.current_org', true)::uuid"
_VIA_NODE_INDIRECT = (
    "node_id IN ("
    "SELECT n.id FROM nodes n"
    " JOIN spaces s ON s.id = n.space_id"
    " JOIN workspaces w ON w.id = s.workspace_id"
    f" WHERE {_VIA_WORKSPACE})"
)


def upgrade() -> None:
    op.create_table(
        "comments",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("author_user_id", sa.UUID(), nullable=True),
        sa.Column("parent_comment_id", sa.UUID(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_comment_id"], ["comments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_comments_node", "comments", ["node_id", "created_at"])

    op.execute(text("ALTER TABLE comments ENABLE ROW LEVEL SECURITY"))
    op.execute(text("ALTER TABLE comments FORCE ROW LEVEL SECURITY"))
    op.execute(
        text(f"CREATE POLICY tenant_isolation ON comments USING ({_UNSET} OR {_VIA_NODE_INDIRECT})")
    )


def downgrade() -> None:
    op.execute(text("DROP POLICY IF EXISTS tenant_isolation ON comments"))
    op.drop_index("idx_comments_node", table_name="comments")
    op.drop_table("comments")
