"""add node_views table

Revision ID: 3ee68ab5ba33
Revises: c58f38d0a5aa
Create Date: 2026-05-16 14:20:54.464066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ee68ab5ba33'
down_revision: Union[str, Sequence[str], None] = 'c58f38d0a5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_views',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('folder_node_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('view_type', sa.Text(), nullable=False),
    sa.Column('position', sa.Text(), server_default='a0', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("view_type IN ('table', 'board', 'list')", name='node_views_view_type_valid'),
    sa.ForeignKeyConstraint(['folder_node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: autogenerate also reported drops for partial / GIN indexes on
    # `nodes` and `org_memberships`. Those indexes are created via raw SQL in
    # earlier migrations and are not reflected by Alembic's comparator — the
    # "removals" are false positives, so they are intentionally omitted here.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('node_views')
