"""add user_stars table

Revision ID: cd990242773c
Revises: c58f38d0a5aa
Create Date: 2026-05-16 21:21:18.103791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd990242773c'
down_revision: Union[str, Sequence[str], None] = 'c58f38d0a5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stars',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'node_id', name='uq_user_stars_user_node')
    )
    # Autogenerate's spurious drops of pre-existing partial indexes
    # (uq_nodes_*_slug, uq_org_memberships_*, idx_nodes_search) were removed —
    # those indexes are intentional and unrelated to this change.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('user_stars')
